name: Bug Report
description: Report a bug or unexpected behavior
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install package
        2. Configure notification preferences with...
        3. Set user preference...
        4. Send notification...
        5. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected the notification to...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your notification preferences config (if relevant)
      render: php
      placeholder: |
        'notifications' => [
            \App\Notifications\OrderShipped::class => [
                'group' => 'system',
                'label' => 'Order Shipped',
            ],
        ]

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: "8.4"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      placeholder: "12.0"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This only happens when...
