name: Update Packagist

on:
  release:
    types: [ published ]

jobs:
  packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist update
        run: |
          curl -X POST https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }} \
               -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}'